---
driver:
  name: docker
  use_sudo: false
  socket: unix:///var/run/docker.sock

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04
    driver_config: 
      username: ubuntu
 
suites:
  - name: default
    run_list:
      - recipe[prime8base::default]
    attributes:

  - name: ubulocal
    run_list:
     - recipe[prime8base::ubuntu]
    attributes:

  - name: ubuec2
    run_list: 
      - recipe[prime8base::ubuntu]
    driver:
      name: ec2
      
