---
driver:
  name: docker
  use_sudo: false
  socket: unix:///var/run/docker.sock

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-16.04
 
suites:
  - name: base-docker
    run_list:
      - recipe[prime8base::default]
      - recipe[prime8base::ubuntu]
    attributes:

  - name: base-ec2
    run_list: 
      - recipe[prime8base::ubuntu]
      - recipe[prime8base::foss_sec]
    driver:
      name: ec2
      region: us-west-2
      aws_ssh_key_id: bootstrap
      instance_type: t2.micro 
      availability_zone: a
      subnet_id: <%= ENV['SUBNET_ID'] %>
      security_group_ids: [ <%= ENV['SECURITY_GROUP_ID'] %> ]
      image_id: <%= ENV['AMI_ID'] %>
      tags: 
        Name: test-prime8base
    transport:
      ssh_key: <%= ENV['SSH_PRIVATE_KEY_FILE'] %> 
      username: ubuntu
