---
driver:
  name: docker
  use_sudo: false
  socket: unix:///var/run/docker.sock
  driver_config: 
    ssh_timeout: 15

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04
    driver_config: 
      username: ubuntu
 
suites:
  - name: default
    run_list:
      - recipe[prime8base::default]
    attributes:

  - name: ubuntu-docker
    run_list:
     - recipe[prime8base::ubuntu]
    attributes:

